name: Context Examples

on:
    push:

jobs:
    my-context:
        runs-on: ubuntu-latest
        steps:
            - name: My first step
              run: |
                echo "Hello! $MY_ACTION"
              env:
                MY_ACTION: ${{ github.action }}
            - name: My second step
              run: |
                echo "Hello! $MY_ACTOR"
              env:
                MY_ACTOR: ${{ github.actor }}