name: Workflow commands

on:
  push:
    branches:
      - main

jobs:
  workflow-job:
    runs-on: ubuntu-latest
    steps:
      - name: group logging
        run: |
          echo "::group::My group message"
          echo "Msg 1"
          echo "Msg 2"
          echo "::endgroup::"
      - name: Set env var step-1
        run: |
          echo "MY_VAL=hello" >> $GITHUB_ENV
      - name: Set env var step-2
        run: |
          echo $MY_VAL
      - name: debug message
        run: |
          echo "::debug::This is a debug message"
      - name: masked message
        run: |
          echo "The masked value is ::add-mask::${{ github.repo }}"
      - name: error message
        run: |
          echo "::error::This is an error message"