name: Workflow commands

on:
  push:
    branches:
      - main

jobs:
  workflow-job:
    runs-on: ubuntu-latest
    steps:
      - name: group logging
        run: |
          echo "::group::My group message"
          echo "Msg 1"
          echo "Msg 2"
          echo "::endgroup::"
      - name: Set env var step-1
        run: |
          echo "MY_VAL=hello" >> $GITHUB_ENV
      - name: Set env var step-2
        run: |
          echo $MY_VAL
      - name: debug message
        run: |
          echo "::debug::This is a debug message"
      - name: masked message
        id: sets-a-secret
        run: |
          the_secret=$((RANDOM))
          echo "::add-mask::$the_secret"
          echo "secret-number=$the_secret" >> "$GITHUB_OUTPUT"
      - name: Use that secret output (protected by a mask)
        run: |
          echo "the secret number is ${{ steps.sets-a-secret.outputs.secret-number }}"
      - name: masked message
        id: sets-another-secret
        run: |
          the_secret=10
          echo "::add-mask::$the_secret"
          echo "secret-number=$the_secret" >> "$GITHUB_OUTPUT"
      - name: Use that secret output (protected by a mask)
        if: ${{ steps.sets-another-secret.outputs.secret-number }} == 10
        run: |
          echo "the other secret number is ${{ steps.sets-another-secret.outputs.secret-number }}"
      - name: error message
        run: |
          echo "::error::This is an error message"